# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins
    build: .
    privileged: true
    user: root
    ports:
    - 8080:8080
    - 50000:50000
    container_name: jenkins
    volumes:
    - ./data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - ./etc/docker/config.json:/root/.docker/config.json

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    ports:
    - 8081:8081
    - 8082:8082
    volumes:
    - ./artifactory/var/:/var/opt/jfrog/artifactory
